In [1]:
import pandas as pd
import numpy as np

# pip install pandas

In [3]:
print(pd.__doc__)

pandas - a powerful data analysis and manipulation library for Python
=====================================================================

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be inserted and deleted from DataFrame and
    higher dimensional objects
  - Automatic and explicit data alignment: objects can be explicitly aligned
    to a set of labels, or the user can simply ignore the labels and let
    `Series`, `DataFrame`, etc. automatically align the data for you in
    computations.
  - Powerful, flexible group by functionality to perform split-apply-combine
    operations on data sets, for both aggregating and transforming data.
  - Make it easy to convert ragged, differently-indexed data in other Python
    and NumPy data structures into DataFrame objects.
  - Intelligent label-based slicing, fancy indexing, and subsetting of large
    data sets.
  - Intuitive merging and joining data sets.
  - Flexible reshaping and pivoting of data sets.
  - Hierarchical labeling of axes (possible to have multiple labels per tick).
  - Robust IO tools for loading data from flat files (CSV and delimited),
    Excel files, databases, and saving/loading data from the ultrafast HDF5
    format.
  - Time series-specific functionality: date range generation and frequency
    conversion, moving window statistics, date shifting and lagging.

In [5]:
arr = np.arange(10)
arr, type(arr), arr.dtype

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray, dtype('int64'))

# Pandas  are Serie & DataFrame

# 1. Series -> este un array specific Pandas (o coloana din tabel)

In [9]:
serie = pd.Series(np.arange(100, 106))
serie

0    100
1    101
2    102
3    103
4    104
5    105
dtype: int64

In [11]:
type(serie), serie.dtype

(pandas.core.series.Series, dtype('int64'))

In [12]:
serie % 2 == 0

0     True
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [13]:
serie[serie % 2 == 0]

0    100
2    102
4    104
dtype: int64

In [14]:
serie + 2

0    102
1    103
2    104
3    105
4    106
5    107
dtype: int64

In [15]:
serie.max(), serie.sum()

(np.int64(105), np.int64(615))

# 2. DataFrame - matrice multidimensionala (un tabel cu mai multe coloane)

In [16]:
df = pd.DataFrame(np.arange(100, 106))
df

     0
0  100
1  101
2  102
3  103
4  104
5  105

In [18]:
type(df), df.dtypes

(pandas.core.frame.DataFrame,
 0    int64
 dtype: object)

In [19]:
df = pd.DataFrame ( {"numere": np.arange(100, 106)})
df

   numere
0     100
1     101
2     102
3     103
4     104
5     105

In [22]:
df = pd.DataFrame([np.arange(100, 106),np.arange(200, 206)])
df

     0    1    2    3    4    5
0  100  101  102  103  104  105
1  200  201  202  203  204  205

In [ ]:
df = pd.DataFrame({"Coloana A": np.arange(100, 106), "Coloana B":np.arange(200, 206)})
df

   Coloana A  Coloana B
0        100        200
1        101        201
2        102        202
3        103        203
4        104        204
5        105        205

In [24]:
df.dtypes

Coloana A    int64
Coloana B    int64
dtype: object

In [25]:
dictionar = {"culori": ["rosu", "verde", "negru", "alb"], "temperaturi":np.random.randint(0, 50, 4)}

df = pd.DataFrame(dictionar)
df

  culori  temperaturi
0   rosu           17
1  verde           38
2  negru           34
3    alb           49

In [26]:
df.dtypes

culori         object
temperaturi     int64
dtype: object

In [27]:
df.min()

culori         alb
temperaturi     17
dtype: object

In [28]:
df.describe()

       temperaturi
count     4.000000
mean     34.500000
std      13.279056
min      17.000000
25%      29.750000
50%      36.000000
75%      40.750000
max      49.000000

# DataFrame-ul poate fi salvat in CSV, JSON, EXCEL..

In [29]:
df.to_numpy()

array([['rosu', 17],
       ['verde', 38],
       ['negru', 34],
       ['alb', 49]], dtype=object)

In [30]:
df.to_dict()

{'culori': {0: 'rosu', 1: 'verde', 2: 'negru', 3: 'alb'},
 'temperaturi': {0: 17, 1: 38, 2: 34, 3: 49}}

In [31]:
df.to_csv()

',culori,temperaturi\n0,rosu,17\n1,verde,38\n2,negru,34\n3,alb,49\n'

In [32]:
df.to_csv("dataframe.csv")

In [33]:
df.to_json("dataframe.json")

In [34]:
df.to_excel("dataframe.xlsx")

In [37]:
dictionar = {"culori": ["rosu", "verde", "negru", "alb", np.nan, np.nan], "temperaturi":np.random.randint(0, 50, 6)}

df = pd.DataFrame(dictionar)
df

  culori  temperaturi
0   rosu           43
1  verde            4
2  negru           23
3    alb            4
4    NaN           34
5    NaN           17

# DataFrame-ul poate citi din CSV, JSON, EXCEL, SQL (MySQL si altele)

In [39]:
df = pd.read_csv("dataframe.csv")
df

   Unnamed: 0  culori  temperaturi
0           0    rosu         17.0
1           1   verde         38.0
2           2   negru         34.0
3           3     alb         49.0
4           4  galben          NaN

In [41]:
df = pd.read_csv("dataframe.csv", index_col=0)
df

   culori  temperaturi
0    rosu         17.0
1   verde         38.0
2   negru         34.0
3     alb         49.0
4  galben          NaN

In [42]:
df.describe()

       temperaturi
count     4.000000
mean     34.500000
std      13.279056
min      17.000000
25%      29.750000
50%      36.000000
75%      40.750000
max      49.000000

In [43]:
df

   culori  temperaturi
0    rosu         17.0
1   verde         38.0
2   negru         34.0
3     alb         49.0
4  galben          NaN

In [45]:
df["temperaturi"] < 45

0     True
1     True
2     True
3    False
4    False
Name: temperaturi, dtype: bool

In [46]:
df[df["temperaturi"] < 45]

  culori  temperaturi
0   rosu         17.0
1  verde         38.0
2  negru         34.0

In [ ]:
df["temperaturi"] # la filtrare pe o singura coloana imi intoarce o serie

0    17.0
1    38.0
2    34.0
3    49.0
4     NaN
Name: temperaturi, dtype: float64

In [49]:
df[["temperaturi"]] # la filtrare pe o singura coloana imi intoarce un DataFrame la doua seturi de paranteza

   temperaturi
0         17.0
1         38.0
2         34.0
3         49.0
4          NaN

In [50]:
df

   culori  temperaturi
0    rosu         17.0
1   verde         38.0
2   negru         34.0
3     alb         49.0
4  galben          NaN

# Filtrare pe rand

In [52]:
df.iloc[3]

culori          alb
temperaturi    49.0
Name: 3, dtype: object

# Filtrare de randuri

In [53]:
df.iloc[1:3]

  culori  temperaturi
1  verde         38.0
2  negru         34.0

In [54]:
df["este_cald"] = df["temperaturi"] > 20
df

   culori  temperaturi  este_cald
0    rosu         17.0      False
1   verde         38.0       True
2   negru         34.0       True
3     alb         49.0       True
4  galben          NaN      False

# Filtreare pe coloana

In [57]:
df[["temperaturi", "este_cald"]] # se creaza un nou dataframe

   temperaturi  este_cald
0         17.0      False
1         38.0       True
2         34.0       True
3         49.0       True
4          NaN      False

In [56]:
df

   culori  temperaturi  este_cald
0    rosu         17.0      False
1   verde         38.0       True
2   negru         34.0       True
3     alb         49.0       True
4  galben          NaN      False