In [1]:
import pandas as pd
import numpy as np

# 1. Citire din CSV

In [3]:
df = pd.read_csv("countries.csv")
df

,country,demonym,id,iso2,tld,currency,population,density,area,gdp,median_age,language,website,calling_code,driving_side,continent,un_member,religion
0,China,Chinese,CN,CN,.cn,Chinese Yuan,1.413143e+09,147.2,9596960.0,17963170.0,39.8,Chinese,https://www.gov.cn,86.0,right,Asia,True,No Religion
1,India,Indian,IN,IN,.in,Indian Rupee,1.399180e+09,425.6,3287263.0,3465541.0,29.5,Hindi,http://india.gov.in,91.0,left,Asia,True,Hinduism
2,United States,American,US,US,.us,United States Dollar,3.396651e+08,34.5,9833517.0,25744100.0,38.5,English,https://www.usa.gov,1.0,right,North America,True,Christianity
3,Indonesia,Indonesian,ID,ID,.id,Rupiah,2.794763e+08,146.7,1904569.0,1319100.0,31.2,Indonesian,https://indonesia.go.id,62.0,left,Asia,True,Islam
4,Pakistan,Pakistani,PK,PK,.pk,Pakistani Rupee,2.476536e+08,311.1,796095.0,326796.0,22.7,Urdu,http://www.pakistan.gov.pk,92.0,left,Asia,True,Islam
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,Réunion,Reunion,RE,RE,.re,Euro,NaN,NaN,NaN,NaN,NaN,French,http://www.regionreunion.com,262.0,right,Africa,False,Christianity
249,South Georgia and the South Sandwich Islands,South Sandwich Islander,GS,GS,.gs,Pound Sterling,NaN,NaN,NaN,NaN,NaN,English,https://gov.gs,7.0,left,Seven seas (open ocean),False,NaN
250,Heard Island and McDonald Islands,NaN,HM,HM,.hm,NaN,NaN,NaN,412.0,NaN,NaN,NaN,https://www.antarctica.gov.au/antarctic-operat...,1.0,left,Seven seas (open ocean),False,NaN
251,Bouvet Island,NaN,BV,BV,.bv,NaN,NaN,NaN,49.0,NaN,NaN,NaN,NaN,NaN,right,Antarctica,False,NaN
252,Antarctica,NaN,AQ,AQ,.aq,NaN,NaN,NaN,14200000.0,NaN,NaN,NaN,http://www.ats.aq,NaN,NaN,Antarctica,False,No Religion

# 2. Afisare a primelor elemente

In [5]:
df.head() # By Default sunt primele 5 elemente

,country,demonym,id,iso2,tld,currency,population,density,area,gdp,median_age,language,website,calling_code,driving_side,continent,un_member,religion
0,China,Chinese,CN,CN,.cn,Chinese Yuan,1.413143e+09,147.2,9596960.0,17963170.0,39.8,Chinese,https://www.gov.cn,86.0,right,Asia,True,No Religion
1,India,Indian,IN,IN,.in,Indian Rupee,1.399180e+09,425.6,3287263.0,3465541.0,29.5,Hindi,http://india.gov.in,91.0,left,Asia,True,Hinduism
2,United States,American,US,US,.us,United States Dollar,3.396651e+08,34.5,9833517.0,25744100.0,38.5,English,https://www.usa.gov,1.0,right,North America,True,Christianity
3,Indonesia,Indonesian,ID,ID,.id,Rupiah,2.794763e+08,146.7,1904569.0,1319100.0,31.2,Indonesian,https://indonesia.go.id,62.0,left,Asia,True,Islam
4,Pakistan,Pakistani,PK,PK,.pk,Pakistani Rupee,2.476536e+08,311.1,796095.0,326796.0,22.7,Urdu,http://www.pakistan.gov.pk,92.0,left,Asia,True,Islam

In [7]:
df.head(2) # Dar pot fi schimbate

,country,demonym,id,iso2,tld,currency,population,density,area,gdp,median_age,language,website,calling_code,driving_side,continent,un_member,religion
0,China,Chinese,CN,CN,.cn,Chinese Yuan,1.413143e+09,147.2,9596960.0,17963170.0,39.8,Chinese,https://www.gov.cn,86.0,right,Asia,True,No Religion
1,India,Indian,IN,IN,.in,Indian Rupee,1.399180e+09,425.6,3287263.0,3465541.0,29.5,Hindi,http://india.gov.in,91.0,left,Asia,True,Hinduism

# 3. Afisare a ultimelor elemente

In [8]:
df.tail(3)

,country,demonym,id,iso2,tld,currency,population,density,area,gdp,median_age,language,website,calling_code,driving_side,continent,un_member,religion
250,Heard Island and McDonald Islands,NaN,HM,HM,.hm,NaN,NaN,NaN,412.0,NaN,NaN,NaN,https://www.antarctica.gov.au/antarctic-operat...,1.0,left,Seven seas (open ocean),False,NaN
251,Bouvet Island,NaN,BV,BV,.bv,NaN,NaN,NaN,49.0,NaN,NaN,NaN,NaN,NaN,right,Antarctica,False,NaN
252,Antarctica,NaN,AQ,AQ,.aq,NaN,NaN,NaN,14200000.0,NaN,NaN,NaN,http://www.ats.aq,NaN,NaN,Antarctica,False,No Religion

# 4. Afisarea unor randuri anume

In [10]:
df.iloc[100:105] # un slice dupa index

,country,demonym,id,iso2,tld,currency,population,density,area,gdp,median_age,language,website,calling_code,driving_side,continent,un_member,religion
100,Togo,Togolese,TG,TG,.tg,West African Cfa Franc,8703961.0,153.3,56785.0,8087.0,20.5,French,https://www.republicoftogo.com,228.0,right,Africa,True,Christianity
101,Switzerland,Swiss,CH,CH,.ch,Swiss Franc,8563760.0,207.5,41277.0,818426.0,44.0,German,https://www.admin.ch,41.0,right,Europe,True,Christianity
102,Laos,Laotian,LA,LA,.la,Lao Kip,7852377.0,33.2,236800.0,15362.0,25.0,Lao,https://www.tourismlaos.org,856.0,right,Asia,True,Buddhism
103,Paraguay,Paraguayan,PY,PY,.py,Paraguayan Guaranã­,7439863.0,18.3,406752.0,41722.0,31.3,Spanish,https://www.paraguay.gov.py,595.0,right,South America,True,Christianity
104,Hong Kong,Hong Konger,HK,HK,.hk,Hong Kong Dollar,7288167.0,6577.8,1108.0,359838.0,46.8,Chinese,http://www.gov.hk,852.0,left,Asia,False,No Religion

# 5. Afisarea numelor de coloane

In [11]:
df.keys()

Index(['country', 'demonym', 'id', 'iso2', 'tld', 'currency', 'population',
       'density', 'area', 'gdp', 'median_age', 'language', 'website',
       'calling_code', 'driving_side', 'continent', 'un_member', 'religion'],
      dtype='object')

# 6. Afisarea doar a unor anumite coloane

In [13]:
df[ ["country", 'currency', 'population']  ] # Prin filtrarea numelor

,country,currency,population
0,China,Chinese Yuan,1.413143e+09
1,India,Indian Rupee,1.399180e+09
2,United States,United States Dollar,3.396651e+08
3,Indonesia,Rupiah,2.794763e+08
4,Pakistan,Pakistani Rupee,2.476536e+08
...,...,...,...
248,Réunion,Euro,NaN
249,South Georgia and the South Sandwich Islands,Pound Sterling,NaN
250,Heard Island and McDonald Islands,NaN,NaN
251,Bouvet Island,NaN,NaN
252,Antarctica,NaN,NaN

# 7. Afisare prin omitirea unor coloane

In [18]:
df.drop(["website", "gdp", "religion"], axis=1) # Axis=1 -> inseamna pe verticala

,country,demonym,id,iso2,tld,currency,population,density,area,median_age,language,calling_code,driving_side,continent,un_member
0,China,Chinese,CN,CN,.cn,Chinese Yuan,1.413143e+09,147.2,9596960.0,39.8,Chinese,86.0,right,Asia,True
1,India,Indian,IN,IN,.in,Indian Rupee,1.399180e+09,425.6,3287263.0,29.5,Hindi,91.0,left,Asia,True
2,United States,American,US,US,.us,United States Dollar,3.396651e+08,34.5,9833517.0,38.5,English,1.0,right,North America,True
3,Indonesia,Indonesian,ID,ID,.id,Rupiah,2.794763e+08,146.7,1904569.0,31.2,Indonesian,62.0,left,Asia,True
4,Pakistan,Pakistani,PK,PK,.pk,Pakistani Rupee,2.476536e+08,311.1,796095.0,22.7,Urdu,92.0,left,Asia,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,Réunion,Reunion,RE,RE,.re,Euro,NaN,NaN,NaN,NaN,French,262.0,right,Africa,False
249,South Georgia and the South Sandwich Islands,South Sandwich Islander,GS,GS,.gs,Pound Sterling,NaN,NaN,NaN,NaN,English,7.0,left,Seven seas (open ocean),False
250,Heard Island and McDonald Islands,NaN,HM,HM,.hm,NaN,NaN,NaN,412.0,NaN,NaN,1.0,left,Seven seas (open ocean),False
251,Bouvet Island,NaN,BV,BV,.bv,NaN,NaN,NaN,49.0,NaN,NaN,NaN,right,Antarctica,False
252,Antarctica,NaN,AQ,AQ,.aq,NaN,NaN,NaN,14200000.0,NaN,NaN,NaN,NaN,Antarctica,False

# 8.Numararea elementelor

In [19]:
df.count()

country         253
demonym         244
id              252
iso2            249
tld             246
currency        245
population      239
density         237
area            242
gdp             206
median_age      225
language        245
website         240
calling_code    238
driving_side    252
continent       250
un_member       253
religion        247
dtype: int64

# 9. Tipurile de date

In [20]:
df.dtypes

country          object
demonym          object
id               object
iso2             object
tld              object
currency         object
population      float64
density         float64
area            float64
gdp             float64
median_age      float64
language         object
website          object
calling_code    float64
driving_side     object
continent        object
un_member          bool
religion         object
dtype: object

# 10. Filtrarea tipurilor numerice

In [21]:
df.dtypes[df.dtypes == "float64"]

population      float64
density         float64
area            float64
gdp             float64
median_age      float64
calling_code    float64
dtype: object

In [26]:
df.dtypes[(df.dtypes == "float64") |(df.dtypes == "int64") |(df.dtypes == "bool") ]

population      float64
density         float64
area            float64
gdp             float64
median_age      float64
calling_code    float64
un_member          bool
dtype: object

# 11. Crearea unor statistici (doar cu valorile numerice)

In [27]:
df.describe()

,population,density,area,gdp,median_age,calling_code
count,2.390000e+02,237.000000,2.420000e+02,2.060000e+02,225.000000,238.000000
mean,3.338174e+07,418.406329,6.234280e+05,4.816300e+05,32.504889,342.180672
std,1.343129e+08,1937.319897,1.951275e+06,2.252735e+06,9.204353,306.882262
min,5.000000e+01,0.000000,0.000000e+00,5.900000e+01,15.100000,1.000000
25%,3.357770e+05,33.500000,1.698500e+03,7.839500e+03,24.800000,57.250000
50%,5.506280e+06,93.400000,6.998650e+04,2.977850e+04,32.300000,255.500000
75%,2.192442e+07,218.500000,4.027532e+05,2.234432e+05,40.600000,590.750000
max,1.413143e+09,22856.100000,1.709824e+07,2.574410e+07,56.200000,998.000000

# 12. Gasirea unor valori unice

In [28]:
df["continent"]

0                         Asia
1                         Asia
2                North America
3                         Asia
4                         Asia
                ...
248                     Africa
249    Seven seas (open ocean)
250    Seven seas (open ocean)
251                 Antarctica
252                 Antarctica
Name: continent, Length: 253, dtype: object

In [30]:
df.continent.unique()

array(['Asia', 'North America', 'Africa', 'South America', 'Europe',
       'Oceania', 'Seven seas (open ocean)', 'Insular Oceania', nan,
       'Antarctica'], dtype=object)

# 13. Numărarea valorilor unice

In [31]:
df.continent.nunique()

9

# 14. Numărarea valorilor lipsă

In [32]:
df.continent.isna()

0      False
1      False
2      False
3      False
4      False
       ...
248    False
249    False
250    False
251    False
252    False
Name: continent, Length: 253, dtype: bool

In [33]:
df.continent.isna().sum()

np.int64(3)

In [34]:
df.isna().sum()

country          0
demonym          9
id               1
iso2             4
tld              7
currency         8
population      14
density         16
area            11
gdp             47
median_age      28
language         8
website         13
calling_code    15
driving_side     1
continent        3
un_member        0
religion         6
dtype: int64

# 15. Filtrarea dupa valori care nu sunt nule

In [36]:
df[~df["population"].isna()]

,country,demonym,id,iso2,tld,currency,population,density,area,gdp,median_age,language,website,calling_code,driving_side,continent,un_member,religion
0,China,Chinese,CN,CN,.cn,Chinese Yuan,1.413143e+09,147.2,9596960.00,17963170.0,39.8,Chinese,https://www.gov.cn,86.0,right,Asia,True,No Religion
1,India,Indian,IN,IN,.in,Indian Rupee,1.399180e+09,425.6,3287263.00,3465541.0,29.5,Hindi,http://india.gov.in,91.0,left,Asia,True,Hinduism
2,United States,American,US,US,.us,United States Dollar,3.396651e+08,34.5,9833517.00,25744100.0,38.5,English,https://www.usa.gov,1.0,right,North America,True,Christianity
3,Indonesia,Indonesian,ID,ID,.id,Rupiah,2.794763e+08,146.7,1904569.00,1319100.0,31.2,Indonesian,https://indonesia.go.id,62.0,left,Asia,True,Islam
4,Pakistan,Pakistani,PK,PK,.pk,Pakistani Rupee,2.476536e+08,311.1,796095.00,326796.0,22.7,Urdu,http://www.pakistan.gov.pk,92.0,left,Asia,True,Islam
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Tokelau,Tokelauan,TK,TK,.tk,New Zealand Dollar,1.647000e+03,137.3,12.00,NaN,NaN,English,https://www.tokelau.org.nz,690.0,left,Insular Oceania,False,Christianity
235,Vatican City,Vatican,VA,VA,.va,Euro,1.000000e+03,NaN,0.00,NaN,NaN,Italian,http://www.vaticanstate.va,39.0,right,Europe,False,Christianity
236,Cocos (Keeling) Islands,Cocos Islander,CC,CC,.cc,Australian Dollar,5.960000e+02,42.6,14.00,NaN,NaN,English,NaN,61.0,left,Oceania,False,Islam
237,United States Minor Outlying Islands,NaN,UM,UM,.um,United States Dollar,3.000000e+02,6.1,49.26,NaN,NaN,English,NaN,NaN,right,North America,False,Christianity
238,Pitcairn Islands,Pitcairn Islander,PN,PN,.pn,New Zealand Dollar,5.000000e+01,1.1,47.00,NaN,NaN,English,https://www.government.pn,64.0,left,Oceania,False,Christianity

# 16. Crearea unui nou DataFrame

In [38]:
country_population_df  = df[~df["population"].isna()][["country", "population"]]
country_population_df

                                  country    population
0                                   China  1.413143e+09
1                                   India  1.399180e+09
2                           United States  3.396651e+08
3                               Indonesia  2.794763e+08
4                                Pakistan  2.476536e+08
..                                    ...           ...
234                               Tokelau  1.647000e+03
235                          Vatican City  1.000000e+03
236               Cocos (Keeling) Islands  5.960000e+02
237  United States Minor Outlying Islands  3.000000e+02
238                      Pitcairn Islands  5.000000e+01

[239 rows x 2 columns]

# 17. Sortarea unui DataFrame dupa coloane

In [39]:
country_population_df.sort_values("country")

            country  population
36      Afghanistan  39232003.0
135         Albania   3101621.0
33          Algeria  44758398.0
211  American Samoa     44620.0
199         Andorra     85468.0
..              ...         ...
138       West Bank   2949246.0
171  Western Sahara    565581.0
46            Yemen  31565602.0
62           Zambia  20216029.0
72         Zimbabwe  15418674.0

[239 rows x 2 columns]

In [41]:
country_population_df.sort_values("population", ascending=False)

                                  country    population
0                                   China  1.413143e+09
1                                   India  1.399180e+09
2                           United States  3.396651e+08
3                               Indonesia  2.794763e+08
4                                Pakistan  2.476536e+08
..                                    ...           ...
234                               Tokelau  1.647000e+03
235                          Vatican City  1.000000e+03
236               Cocos (Keeling) Islands  5.960000e+02
237  United States Minor Outlying Islands  3.000000e+02
238                      Pitcairn Islands  5.000000e+01

[239 rows x 2 columns]

# 18. Salvarea unui fisier csv

In [42]:
country_population_df.sort_values("country").to_csv("countries_population.csv")

# 19. Citirea unui fisier csv dintr-un link

In [44]:
URL = "https://raw.githubusercontent.com/sojog/Data-Analysis-and-Processing-using-Python-Link-2026/refs/heads/main/Curs3/countries_population.csv"


pd.read_csv(URL, index_col=0)

            country  population
36      Afghanistan  39232003.0
135         Albania   3101621.0
33          Algeria  44758398.0
211  American Samoa     44620.0
199         Andorra     85468.0
..              ...         ...
138       West Bank   2949246.0
171  Western Sahara    565581.0
46            Yemen  31565602.0
62           Zambia  20216029.0
72         Zimbabwe  15418674.0

[239 rows x 2 columns]