In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.read_csv("https://randomuser.me/api/?format=csv")

,gender,name.title,name.first,name.last,location.street.number,location.street.name,location.city,location.state,location.country,location.postcode,...,registered.date,registered.age,phone,cell,id.name,id.value,picture.large,picture.medium,picture.thumbnail,nat
0,male,Mr,Hasso,Thiel,5233,Breslauer Straße,Rüthen,Rheinland-Pfalz,Germany,48308,...,2006-05-05T22:57:26.732Z,19,0076-0478590,0179-1051116,SVNR,42 180156 T 451,https://randomuser.me/api/portraits/men/13.jpg,https://randomuser.me/api/portraits/med/men/13...,https://randomuser.me/api/portraits/thumb/men/...,DE

# 1.  Downloadați 500 de utilizatori în format CSV

In [4]:
df = pd.read_csv("https://randomuser.me/api/?format=csv&results=500")
df

,gender,name.title,name.first,name.last,location.street.number,location.street.name,location.city,location.state,location.country,location.postcode,...,registered.date,registered.age,phone,cell,id.name,id.value,picture.large,picture.medium,picture.thumbnail,nat
0,male,Mr,Melvin,Garcia,8596,Voksenkollveien,Straume,Hedmark,Norway,0509,...,2021-02-14T07:43:25.863Z,5,77195348,42998486,FN,20129707977,https://randomuser.me/api/portraits/men/26.jpg,https://randomuser.me/api/portraits/med/men/26...,https://randomuser.me/api/portraits/thumb/men/...,NO
1,male,Monsieur,Claudio,Henry,5275,Rue Bony,Wiliberg,Genève,Switzerland,6408,...,2002-11-04T00:33:42.391Z,23,077 006 65 91,079 519 10 47,AVS,756.1890.5520.98,https://randomuser.me/api/portraits/men/75.jpg,https://randomuser.me/api/portraits/med/men/75...,https://randomuser.me/api/portraits/thumb/men/...,CH
2,male,Mr,Marcus,Syrstad,2240,Moserabben,Grøa,Nord-Trøndelag,Norway,3885,...,2006-06-15T23:18:52.404Z,19,64187281,94886463,FN,07039913741,https://randomuser.me/api/portraits/men/33.jpg,https://randomuser.me/api/portraits/med/men/33...,https://randomuser.me/api/portraits/thumb/men/...,NO
3,male,Mr,Hans-Hermann,Weißbach,1171,Kirchplatz,Schwaigern,Sachsen-Anhalt,Germany,83113,...,2020-06-15T21:53:09.172Z,5,0435-8143046,0178-1929942,SVNR,24 150697 W 202,https://randomuser.me/api/portraits/men/64.jpg,https://randomuser.me/api/portraits/med/men/64...,https://randomuser.me/api/portraits/thumb/men/...,DE
4,female,Mrs,Ayşe,Sezek,4545,Maçka Cd,Elazığ,Aksaray,Turkey,87197,...,2015-10-08T13:28:20.472Z,10,(914)-799-4220,(853)-993-4515,NaN,NaN,https://randomuser.me/api/portraits/women/11.jpg,https://randomuser.me/api/portraits/med/women/...,https://randomuser.me/api/portraits/thumb/wome...,TR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,male,Mr,Leroy,Brewer,5751,W Belt Line Rd,Cairns,Northern Territory,Australia,1449,...,2019-03-12T17:03:53.392Z,6,03-3478-2141,0471-893-185,TFN,017271409,https://randomuser.me/api/portraits/men/8.jpg,https://randomuser.me/api/portraits/med/men/8.jpg,https://randomuser.me/api/portraits/thumb/men/...,AU
496,male,Mr,Tommy,Murphy,9552,Lone Wolf Trail,Rockhampton,Western Australia,Australia,5750,...,2004-01-03T02:44:22.079Z,22,08-7551-2250,0413-530-110,TFN,374077569,https://randomuser.me/api/portraits/men/45.jpg,https://randomuser.me/api/portraits/med/men/45...,https://randomuser.me/api/portraits/thumb/men/...,AU
497,male,Mr,Alexandre,Taylor,3992,Queen St,Inverness,Alberta,Canada,W7N 4J4,...,2005-04-27T16:07:05.727Z,20,A10 K47-4746,K17 R14-4518,SIN,444181499,https://randomuser.me/api/portraits/men/21.jpg,https://randomuser.me/api/portraits/med/men/21...,https://randomuser.me/api/portraits/thumb/men/...,CA
498,male,Mr,Matthew,Sirko,211,15th St,Vanier,Ontario,Canada,I0X 8R4,...,2011-04-05T18:03:47.581Z,14,Z36 T37-7802,R11 J63-0052,SIN,136398518,https://randomuser.me/api/portraits/men/96.jpg,https://randomuser.me/api/portraits/med/men/96...,https://randomuser.me/api/portraits/thumb/men/...,CA
499,female,Miss,Drishti,Saha,367,Shakespeare Sarani,Allahabad,Tripura,India,24702,...,2014-06-22T19:55:49.807Z,11,7193099753,9622479023,UIDAI,458025476273,https://randomuser.me/api/portraits/women/49.jpg,https://randomuser.me/api/portraits/med/women/...,https://randomuser.me/api/portraits/thumb/wome...,IN

# 2. Afișați țările de unde sunt acești utilizatori

In [5]:
df["location.country"]

0           Norway
1      Switzerland
2           Norway
3          Germany
4           Turkey
          ...
495      Australia
496      Australia
497         Canada
498         Canada
499          India
Name: location.country, Length: 500, dtype: object

In [6]:
df["location.country"].unique()

array(['Norway', 'Switzerland', 'Germany', 'Turkey', 'Brazil',
       'United States', 'India', 'Ukraine', 'United Kingdom', 'Canada',
       'Iran', 'Ireland', 'New Zealand', 'Denmark', 'Finland', 'Spain',
       'Mexico', 'Serbia', 'Australia', 'France', 'Netherlands'],
      dtype=object)

In [8]:
print(set(df["location.country"]))

{'New Zealand', 'Denmark', 'Netherlands', 'Spain', 'Mexico', 'India', 'Australia', 'Ireland', 'Canada', 'Serbia', 'Brazil', 'United States', 'Ukraine', 'Germany', 'Norway', 'Iran', 'United Kingdom', 'France', 'Finland', 'Switzerland', 'Turkey'}

In [10]:
countries = df["location.country"].unique()
countries.sort()
countries

array(['Australia', 'Brazil', 'Canada', 'Denmark', 'Finland', 'France',
       'Germany', 'India', 'Iran', 'Ireland', 'Mexico', 'Netherlands',
       'New Zealand', 'Norway', 'Serbia', 'Spain', 'Switzerland',
       'Turkey', 'Ukraine', 'United Kingdom', 'United States'],
      dtype=object)

# 3. Filtrați doar utilizatorii din USA

In [14]:
us_df = df [ df["location.country"] == 'United States']
us_df.head(2)

,gender,name.title,name.first,name.last,location.street.number,location.street.name,location.city,location.state,location.country,location.postcode,...,registered.date,registered.age,phone,cell,id.name,id.value,picture.large,picture.medium,picture.thumbnail,nat
7,male,Mr,Bruce,Alvarez,4148,Dane St,Anchorage,Nevada,United States,29376,...,2020-03-20T04:56:47.450Z,5,(880) 919-2392,(919) 649-5027,SSN,797-22-1569,https://randomuser.me/api/portraits/men/71.jpg,https://randomuser.me/api/portraits/med/men/71...,https://randomuser.me/api/portraits/thumb/men/...,US
75,female,Miss,Yvonne,Hughes,8876,Hamilton Ave,Iowa Park,Rhode Island,United States,19395,...,2011-02-20T11:57:05.007Z,15,(599) 588-3405,(945) 226-9938,SSN,710-28-6022,https://randomuser.me/api/portraits/women/51.jpg,https://randomuser.me/api/portraits/med/women/...,https://randomuser.me/api/portraits/thumb/wome...,US

In [15]:
us_df.count()

gender                            24
name.title                        24
name.first                        24
name.last                         24
location.street.number            24
location.street.name              24
location.city                     24
location.state                    24
location.country                  24
location.postcode                 24
location.coordinates.latitude     24
location.coordinates.longitude    24
location.timezone.offset          24
location.timezone.description     24
email                             24
login.uuid                        24
login.username                    24
login.password                    24
login.salt                        24
login.md5                         24
login.sha1                        24
login.sha256                      24
dob.date                          24
dob.age                           24
registered.date                   24
registered.age                    24
phone                             24
cell                              24
id.name                           24
id.value                          24
picture.large                     24
picture.medium                    24
picture.thumbnail                 24
nat                               24
dtype: int64