In [108]:
import pandas as pd

In [109]:
# 1. Importați fișierul CSV folosind Pandas și afișați primele 5 rânduri. 

df = pd.read_csv("clwin.csv", index_col="id")
df.head()

    country        team  trophies
id
0   England   Liverpool       6.0
1     Spain   Barcelona       5.0
2   England  Man United       3.0
3     Italy       Inter       3.0
4   England     Chelsea       2.0

In [110]:
# 2. Afișați tipurile de date ale fiecărei coloane. 
df.dtypes

country      object
team         object
trophies    float64
dtype: object

In [111]:
# 3. Obțineți statisticile rezumate ale coloanelor numerice din date. 
df.describe()

        trophies
count  19.000000
mean    2.000000
std     1.414214
min     1.000000
25%     1.000000
50%     2.000000
75%     2.000000
max     6.000000

In [112]:
df.count()

country     20
team        20
trophies    19
dtype: int64

In [113]:
df.min()

country         England
team        Aston Villa
trophies            1.0
dtype: object

In [114]:
# 4. Verificați dacă există valori lipsă în setul de date. 
df.isna().sum()

country     0
team        0
trophies    1
dtype: int64

In [115]:
df[df["trophies"].isna()]

    country  team  trophies
id
17  Romania  FCSB       NaN

In [116]:
# 5. Numărați câte echipe se află în total
df["country"].count()

np.int64(20)

In [117]:
# 6. Selectați și afișați coloanele „echipă” și „trofee”. 
df.keys()

Index(['country', 'team', 'trophies'], dtype='object')

In [118]:
df[ ["team", "trophies"] ].head(2)

         team  trophies
id
0   Liverpool       6.0
1   Barcelona       5.0

In [119]:
df[ ["team", "trophies"] ].rename(columns={"team":"echipa", "trophies":"trofee"})

           echipa  trofee
id
0       Liverpool     6.0
1       Barcelona     5.0
2      Man United     3.0
3           Inter     3.0
4         Chelsea     2.0
5         Chelsea     2.0
6    Nottm Forest     2.0
7         Benfica     2.0
8        Juventus     2.0
9        FC Porto     2.0
10       Man City     1.0
11       Dortmund     1.0
12      Feyenoord     1.0
13      Marseille     1.0
14    Aston Villa     1.0
15        Hamburg     1.0
16  Crvena zvezda     1.0
17           FCSB     NaN
18            PSV     1.0
19         Celtic     1.0

In [120]:
# 7. Selectați rândurile în care țara este „Anglia”. 

df[df["country"] == "England"]

    country          team  trophies
id
0   England     Liverpool       6.0
2   England    Man United       3.0
4   England       Chelsea       2.0
5   England       Chelsea       2.0
6   England  Nottm Forest       2.0
10  England      Man City       1.0
14  England   Aston Villa       1.0

In [121]:
# 8. Afișează rândurile în care „trofeele” sunt mai mari decât 2. 
cel_putin_2_trofee = df["trophies"] > 2
df[cel_putin_2_trofee]

    country        team  trophies
id
0   England   Liverpool       6.0
1     Spain   Barcelona       5.0
2   England  Man United       3.0
3     Italy       Inter       3.0

In [122]:

# 9. Accesați coloanele „echipă” și „țară” pentru primele 10 rânduri. 
df[["team", "country"]].head(10)

            team   country
id
0      Liverpool   England
1      Barcelona     Spain
2     Man United   England
3          Inter     Italy
4        Chelsea   England
5        Chelsea   England
6   Nottm Forest   England
7        Benfica  Portugal
8       Juventus     Italy
9       FC Porto  Portugal

In [123]:
df[["team", "country"]][:10]

            team   country
id
0      Liverpool   England
1      Barcelona     Spain
2     Man United   England
3          Inter     Italy
4        Chelsea   England
5        Chelsea   England
6   Nottm Forest   England
7        Benfica  Portugal
8       Juventus     Italy
9       FC Porto  Portugal

# iloc -> indexlocation

In [124]:
df[["team", "country"]].iloc[:10]

            team   country
id
0      Liverpool   England
1      Barcelona     Spain
2     Man United   England
3          Inter     Italy
4        Chelsea   England
5        Chelsea   England
6   Nottm Forest   England
7        Benfica  Portugal
8       Juventus     Italy
9       FC Porto  Portugal

In [125]:
# 10. Selectați ultimele 5 rânduri ale DataFrame. 
df.tail()

        country           team  trophies
id
15      Germany        Hamburg       1.0
16       Serbia  Crvena zvezda       1.0
17      Romania           FCSB       NaN
18  Netherlands            PSV       1.0
19     Scotland         Celtic       1.0

In [126]:
df[-5:]

        country           team  trophies
id
15      Germany        Hamburg       1.0
16       Serbia  Crvena zvezda       1.0
17      Romania           FCSB       NaN
18  Netherlands            PSV       1.0
19     Scotland         Celtic       1.0

In [127]:
df.iloc[-5:]

        country           team  trophies
id
15      Germany        Hamburg       1.0
16       Serbia  Crvena zvezda       1.0
17      Romania           FCSB       NaN
18  Netherlands            PSV       1.0
19     Scotland         Celtic       1.0

In [128]:
# 11. Filtrați echipele din „Spania” și afișați-le datele. 

df["country"].unique()

array(['England', 'Spain', 'Italy', 'Portugal', 'Germany', 'Netherlands',
       'France', 'Serbia', 'Romania', 'Scotland'], dtype=object)

In [129]:
df[df["country"] == "Spain"]

   country       team  trophies
id
1    Spain  Barcelona       5.0

In [130]:
df

        country           team  trophies
id
0       England      Liverpool       6.0
1         Spain      Barcelona       5.0
2       England     Man United       3.0
3         Italy          Inter       3.0
4       England        Chelsea       2.0
5       England        Chelsea       2.0
6       England   Nottm Forest       2.0
7      Portugal        Benfica       2.0
8         Italy       Juventus       2.0
9      Portugal       FC Porto       2.0
10      England       Man City       1.0
11      Germany       Dortmund       1.0
12  Netherlands      Feyenoord       1.0
13       France      Marseille       1.0
14      England    Aston Villa       1.0
15      Germany        Hamburg       1.0
16       Serbia  Crvena zvezda       1.0
17      Romania           FCSB       NaN
18  Netherlands            PSV       1.0
19     Scotland         Celtic       1.0

# Adaugarea unei noi intrari in pandas

In [131]:
df.loc[20] = ["Spain", "Real Madrid", 15]
df

        country           team  trophies
id
0       England      Liverpool       6.0
1         Spain      Barcelona       5.0
2       England     Man United       3.0
3         Italy          Inter       3.0
4       England        Chelsea       2.0
5       England        Chelsea       2.0
6       England   Nottm Forest       2.0
7      Portugal        Benfica       2.0
8         Italy       Juventus       2.0
9      Portugal       FC Porto       2.0
10      England       Man City       1.0
11      Germany       Dortmund       1.0
12  Netherlands      Feyenoord       1.0
13       France      Marseille       1.0
14      England    Aston Villa       1.0
15      Germany        Hamburg       1.0
16       Serbia  Crvena zvezda       1.0
17      Romania           FCSB       NaN
18  Netherlands            PSV       1.0
19     Scotland         Celtic       1.0
20        Spain    Real Madrid      15.0

# Sortare dupa o anumita coloana

In [132]:
df = df.sort_values("trophies", ascending=False) # creaza un nou dataframe
df

        country           team  trophies
id
20        Spain    Real Madrid      15.0
0       England      Liverpool       6.0
1         Spain      Barcelona       5.0
2       England     Man United       3.0
3         Italy          Inter       3.0
4       England        Chelsea       2.0
5       England        Chelsea       2.0
6       England   Nottm Forest       2.0
7      Portugal        Benfica       2.0
8         Italy       Juventus       2.0
9      Portugal       FC Porto       2.0
15      Germany        Hamburg       1.0
19     Scotland         Celtic       1.0
18  Netherlands            PSV       1.0
16       Serbia  Crvena zvezda       1.0
11      Germany       Dortmund       1.0
14      England    Aston Villa       1.0
13       France      Marseille       1.0
12  Netherlands      Feyenoord       1.0
10      England       Man City       1.0
17      Romania           FCSB       NaN

# Reindexare

In [133]:
df.reset_index().head(2)

   id  country         team  trophies
0  20    Spain  Real Madrid      15.0
1   0  England    Liverpool       6.0

# Reindexare cu renuntarea la vechiul index (drop)

In [134]:
df = df.reset_index(drop=True)
df.head(3)

   country         team  trophies
0    Spain  Real Madrid      15.0
1  England    Liverpool       6.0
2    Spain    Barcelona       5.0

# Verificarea valorilor duplicate

In [135]:
df[df.duplicated()]

   country     team  trophies
6  England  Chelsea       2.0

In [136]:
df.iloc[5:7]

   country     team  trophies
5  England  Chelsea       2.0
6  England  Chelsea       2.0

# Eliminarea valorilor duplicate

In [137]:
df = df.drop_duplicates()
df

        country           team  trophies
0         Spain    Real Madrid      15.0
1       England      Liverpool       6.0
2         Spain      Barcelona       5.0
3       England     Man United       3.0
4         Italy          Inter       3.0
5       England        Chelsea       2.0
7       England   Nottm Forest       2.0
8      Portugal        Benfica       2.0
9         Italy       Juventus       2.0
10     Portugal       FC Porto       2.0
11      Germany        Hamburg       1.0
12     Scotland         Celtic       1.0
13  Netherlands            PSV       1.0
14       Serbia  Crvena zvezda       1.0
15      Germany       Dortmund       1.0
16      England    Aston Villa       1.0
17       France      Marseille       1.0
18  Netherlands      Feyenoord       1.0
19      England       Man City       1.0
20      Romania           FCSB       NaN

# Reindexare cu renuntarea la vechiul index (drop)

In [138]:
df.reset_index(drop=True) # Aici se creeaza un nou dataframe

        country           team  trophies
0         Spain    Real Madrid      15.0
1       England      Liverpool       6.0
2         Spain      Barcelona       5.0
3       England     Man United       3.0
4         Italy          Inter       3.0
5       England        Chelsea       2.0
6       England   Nottm Forest       2.0
7      Portugal        Benfica       2.0
8         Italy       Juventus       2.0
9      Portugal       FC Porto       2.0
10      Germany        Hamburg       1.0
11     Scotland         Celtic       1.0
12  Netherlands            PSV       1.0
13       Serbia  Crvena zvezda       1.0
14      Germany       Dortmund       1.0
15      England    Aston Villa       1.0
16       France      Marseille       1.0
17  Netherlands      Feyenoord       1.0
18      England       Man City       1.0
19      Romania           FCSB       NaN

# Reindexare IN PLACE cu renuntarea la vechiul index (drop)

In [139]:
df.reset_index(drop=True, inplace=True) # nu returneaza nimic, dar executa functia si o aplica DataFrame-ului

In [140]:
df

        country           team  trophies
0         Spain    Real Madrid      15.0
1       England      Liverpool       6.0
2         Spain      Barcelona       5.0
3       England     Man United       3.0
4         Italy          Inter       3.0
5       England        Chelsea       2.0
6       England   Nottm Forest       2.0
7      Portugal        Benfica       2.0
8         Italy       Juventus       2.0
9      Portugal       FC Porto       2.0
10      Germany        Hamburg       1.0
11     Scotland         Celtic       1.0
12  Netherlands            PSV       1.0
13       Serbia  Crvena zvezda       1.0
14      Germany       Dortmund       1.0
15      England    Aston Villa       1.0
16       France      Marseille       1.0
17  Netherlands      Feyenoord       1.0
18      England       Man City       1.0
19      Romania           FCSB       NaN

In [141]:
df.keys()

Index(['country', 'team', 'trophies'], dtype='object')

# Crearea unui DataFrame folosind liste

In [142]:
big_df = pd.DataFrame([["Italy", "AC Milan", 7], ["Germany", "Bayern Munchen", 6]], columns=['country', 'team', 'trophies'])
big_df

   country            team  trophies
0    Italy        AC Milan         7
1  Germany  Bayern Munchen         6

# Crearea unui DataFrame folosind dictionar

In [143]:
dictionar = {"country":["Italy", "Germany"], 
             "team":["AC Milan", "Bayern Munchen"],
              "trophies" :[7, 6]}


big_df = pd.DataFrame(dictionar)
big_df

   country            team  trophies
0    Italy        AC Milan         7
1  Germany  Bayern Munchen         6

# Combinare a 2 DataFrame -uri

In [144]:
df.head(2)

   country         team  trophies
0    Spain  Real Madrid      15.0
1  England    Liverpool       6.0

In [148]:
merged_df = pd.concat([big_df, df])
merged_df.head()

   country            team  trophies
0    Italy        AC Milan       7.0
1  Germany  Bayern Munchen       6.0
0    Spain     Real Madrid      15.0
1  England       Liverpool       6.0
2    Spain       Barcelona       5.0

# Sortare dupa mai multe criterii

In [154]:
# In ordinea celor mai multe trofee, apoi alfabetic dupa tara
merged_df.sort_values(["trophies", "country"], ascending=[False, True], inplace=True)

In [155]:
merged_df = merged_df.reset_index(drop=True)
merged_df

        country            team  trophies
0         Spain     Real Madrid      15.0
1         Italy        AC Milan       7.0
2       England       Liverpool       6.0
3       Germany  Bayern Munchen       6.0
4         Spain       Barcelona       5.0
5       England      Man United       3.0
6         Italy           Inter       3.0
7       England         Chelsea       2.0
8       England    Nottm Forest       2.0
9         Italy        Juventus       2.0
10     Portugal         Benfica       2.0
11     Portugal        FC Porto       2.0
12      England     Aston Villa       1.0
13      England        Man City       1.0
14       France       Marseille       1.0
15      Germany         Hamburg       1.0
16      Germany        Dortmund       1.0
17  Netherlands             PSV       1.0
18  Netherlands       Feyenoord       1.0
19     Scotland          Celtic       1.0
20       Serbia   Crvena zvezda       1.0
21      Romania            FCSB       NaN